services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: notely-frontend-prod
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
