FROM node:20-alpine

USER root

WORKDIR /app

RUN addgroup -g 1001 -S appGroup && adduser -u 1001 -S appUser -G appGroup

COPY package*.json ./

RUN npm install

COPY . .

RUN chown -R appUser:appGroup /app

USER appUser

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
