services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: notely-frontend-dev
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
